### ISSUE TITLE
Issue with Rugged 0.22

### ISSUE THREAD

**Issue by stim371** [mmozuras/pronto-poper#3]
I just ran into https://github.com/libgit2/rugged/issues/475, and it looks like it can be fixed by bumping the rugged version.

There's an open pr with the main pronto repo to bump the version, but I'm curious why the gemspec is so locked down. If the rugged dependency was `~> 0.22`, doing a `bundle install` would have picked up 0.23 easily.

**Comment by mmozuras** [comment]
@stim371 released versions of `poper` and `pronto` that work with `0.23`. `bundle update` should fix it for you. Sorry for taking a while, I've been on a long vacation :smile: 

`rugged` only changes MINOR and PATCH version numbers, but those haven't always been backwards compatible. Of course, I'd listen to an argument to change my ways :smile:

**Comment by stim371** [comment]
@mmozuras I didn't realize rugged didn't adhere to semver. I would hope https://github.com/libgit2/rugged/issues/472 gets approved so the constraint for downstream users could be relaxed.
